### ISSUE TITLE
Support mapping output type of `ref:(...)` as a reference

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/lutaml-model#333]
There are occasions where a serialization is not meant to serialize child attributes as objects, but as references.

```ruby
class Publication < Lutaml::Model::Serializable
  attribute :id, :string
  attribute :related_items, ref(Publication, :id), collection: true
end
```

```yaml
books:
- id: doi-1234
  title: This is a Book
  related_items:
    - doi-2345
    - doi-3456
- id: doi-2345
  title: This is also a Book
  related_items:
    - doi-1234
```

This was last encountered when a reference to a `parent` was needed:
* https://github.com/lutaml/expressir/pull/230

It makes me wonder if `ref:` is an "attribute value type" or a "mapping value type"?

**Comment by kwkwan** [comment]
You may reference this below part to see `Glossarist::ManagedConceptData` is now using id to link with `localizations`.

[class ManagedConceptData < Lutaml::Model::Serializable](https://github.com/glossarist/glossarist-ruby/blob/8207709dcfbf4958a68570f41129b60354459d5d/lib/glossarist/managed_concept_data.rb#L2-L38)

**Comment by ronaldtse** [comment]
This is now getting important due to #436 , within a YAML Stream file we will need to be able to cross/inter-link objects.

**Comment by HassanAkbar** [comment]
@ronaldtse I have a question related to this.

If we have two different collections i.e. `concepts` and `localized_concepts`, how does the `concept` collection know about the `localized_concepts` collection?

**For example:**

we have the following `lutaml-models`

```ruby
class LocalizeConcept < Lutaml::Model::Serializable
  attribute :id, :string
  attribute :language, :string
  attribute :localized_name, :string
end

class Concept < Lutaml::Model::Serializable
  attribute :id, :string
  attribute :localized_concepts, ref(LocalizeConcept, :id), collection: true
end
```

and `concepts.yaml` is

```yaml
concepts:
  - id: "1"
    localized_concepts:
      - "1-en"
      - "1-fr"
  - id: "2"
    localized_concepts:
      - "2-en"

```

and `localized_concepts.yaml` is

```yaml
# localized_concepts.yml
localized_concepts:
  - id: "1-en"
    language: "en"
    localized_name: "Concept 1 in English"
  - id: "1-fr"
    language: "fr"
    localized_name: "Concept 1 in French"
  - id: "2-en"
    language: "en"
    localized_name: "Concept 2 in English"
```

and if we do this

```ruby
concepts = Concept.from_yaml(concept_yaml)
localized_concepts = LocalizeConcept.from_yaml(localized_concepts_yaml)
```

Then how do we tell the `Concept` instances about the `localized_concepts` collection, which is loaded separately?

If everything is included in a single YAML source, what would the corresponding lutaml-model definitions look like?
